"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.75;
const nacionalidade = 'brasileiro';
const colegas = ['lucas', 'fernanda',];
const tecnologia = ['html', 'css', 'js'];
const notas = [7, 9, 5, 8];
const lista = ['gian', true, 27];
let idadeDaAna = 25;
idadeDaAna = '25 anos';
let curso = 'front end';
